---
title: "References of PAG 2024 poster"
subtitle: "Investigating Ploidy and Aneuploidy Patterns Among Rosa spp. and the Effect on Linkage Analysis"
output: html_document
date: "2024-01-06"
---

* Leroy, T., Albert, E., Thouroude, T., Baudino, S., Caissard, J.-C., Chastellier, A., Chameau, J., Jeauffre, J., Loubert, T., Nindya Paramita, S., Pernet, A., Soufflet-Freslon, V., Oghina-Pavie, C., Foucher, F., Hibrand-Saint Oyant, L., & Clotault, J. (2023). Dark side of the honeymoon: reconstructing the Asian x European rose breeding history through the lens of genomics. BioRxiv. https://doi.org/10.1101/2023.06.22.546162

* Lau J., Young E. L., Collins S., Windham M. T., Klein P. E., Byrne D. H., Riera-Lizarazu O. Rose Rosette Disease Resistance Loci Detected in Two Interconnected Tetraploid Garden Rose Populations. Frontiers in Plant Science 13 (2022). https://10.3389/fpls.2022.916231 

* Lau J, Gill H, Taniguti CH, Young EL, Klein PE, Byrne DH, Riera-Lizarazu O. QTL discovery for resistance to black spot and cercospora leaf spot, and defoliation in two interconnected F1 bi-parental tetraploid garden rose populations. Front Plant Sci. 2023 Jul 27;14:1209445. doi: 10.3389/fpls.2023.1209445. PMID: 37575936; PMCID: PMC10413565.

* Voorrips, R.E., Gort, G. & Vosman, B. Genotype calling in tetraploid species from bi-allelic marker data using mixture models. BMC Bioinformatics 12, 172 (2011). https://doi.org/10.1186/1471-2105-12-172

* Wang K, Li M, Hadley D, Liu R, Glessner J, Grant SF, Hakonarson H, Bucan M. PennCNV: an integrated hidden Markov model designed for high-resolution copy number variation detection in whole-genome SNP genotyping data. Genome Res. 2007 Nov;17(11):1665-74. doi: 10.1101/gr.6861907. Epub 2007 Oct 5. PMID: 17921354; PMCID: PMC2045149.

* Stefano Colella, Christopher Yau, Jennifer M. Taylor, Ghazala Mirza, Helen Butler, Penny Clouston, Anne S. Bassett, Anneke Seller, Christopher C. Holmes, Jiannis Ragoussis, QuantiSNP: an Objective Bayes Hidden-Markov Model to detect and accurately map copy number variation using SNP genotyping data, Nucleic Acids Research, Volume 35, Issue 6, 15 March 2007, Pages 2013–2025, https://doi.org/10.1093/nar/gkm076

* Korn, J., Kuruvilla, F., McCarroll, S. et al. Integrated genotype calling and association analysis of SNPs, common copy number polymorphisms and rare CNVs. Nat Genet 40, 1253–1260 (2008). https://doi.org/10.1038/ng.237

* Laura Balagué-Dobón, Alejandro Cáceres, Juan R González, Fully exploiting SNP arrays: a systematic review on the tools to extract underlying genomic structure, Briefings in Bioinformatics, Volume 23, Issue 2, March 2022, bbac043, https://doi.org/10.1093/bib/bbac043